# Generated by Django 5.2.10 on 2026-01-18 14:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-pub_date']},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='choice',
        ),
        migrations.AddField(
            model_name='poll',
            name='allow_multiple',
            field=models.BooleanField(default=False, help_text='Allow users to select multiple choices'),
        ),
        migrations.AddField(
            model_name='poll',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_polls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poll',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this poll should close (optional)', null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Manually deactivate a poll if needed'),
        ),
        migrations.AddField(
            model_name='vote',
            name='choices',
            field=models.ManyToManyField(related_name='votes_received', to='polls.choice'),
        ),
        migrations.AddField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(max_length=300),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['poll', 'user'], name='polls_vote_poll_id_cfe401_idx'),
        ),
    ]
